name    'puppet-docker'
version '0.1.0'
source 'UNKNOWN'
author 'puppet'
license 'Apache License, Version 2.0'
summary 'A Puppet Module to install Docker on Ubuntu 13.10'
description 'A Puppet Module to install Docker on Ubuntu 13.10'
dependency 'puppetlabs/apt'
